version: '3.8'
services:
  postgres-db:
    image: postgres:16
    container_name: insurance_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: insurance_db
    ports:
      - "5433:5432"
    restart: unless-stopped


  backend:
    build: ./backend
    container_name: insurance_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/insurance_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  frontend:
    build: ./frontend
    container_name: insurance_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
